name: Check XML Files
on:
  pull_request:
    branches:
    - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check meta-xmls
      run: |
        echo "running.."
        echo ${{ github.repository }}
        echo ${{ github.event.pull_request.number }}
        echo ${{ steps.files.outputs.all }}
        
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
               --header 'content-type: application/json' | jq -r '.[] | .filename')
        
        echo "$FILES"
        
        if [ echo $FILES | grep -q ".xml"; ]
        then
          echo "XML Files found"
          exit 0
        else
          echo "XML Files Not found"
          exit 0
        fi
        
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done
