name: Check XML Files
on:
  pull_request:
    branches:
    - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check meta-xmls
      run: |
        echo "running.."
        echo ${{ github.repository }}
