name: Check TrackTrending Enabled in Objects
on:
  pull_request:
    branches:
    - 'main'
jobs:
  Fetch-and-check-the-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch all xml files
      id: changed_files
      run: |
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
               --header 'content-type: application/json' | jq '.[] | select(.filename | endswith(".xml")) | .filename')
        echo "$FILES"
        echo "files=$(echo $FILES)" >> $GITHUB_OUTPUT
        
    - name: Check for track trending enabled
      run: |
        filesFound="false"
        for file in $(echo "${{ steps.changed_files.outputs.files }}"); do
          echo "- $file"
          if grep -i "<trackTrending>true</trackTrending>" $file;
          then
            filesFound="true"
            echo "ERROR --->>> trackTrending enabled in : $file"
          fi
        done
        if [ $filesFound == "true" ]
        then
          echo "Please disable trackTrending from the meta files"
          exit 1
        else
          exit 0
        fi
                        
      
